import { TranslationDictionary, MenuCategory, WineCategory } from './types';

export const translations: Record<'es' | 'en', TranslationDictionary> = {
  es: {
    nav: {
      home: 'Inicio',
      essence: 'La Esencia',
      menu: 'El Menú',
      wine: 'Carta de Vinos',
      gallery: 'Galería',
      chef: 'El Chef',
      contact: 'Contacto',
      book: 'Reservar Mesa',
    },
    hero: {
      subtitle: 'LUMINARA RISTORANTE',
      titleAccent: 'Donde la tradición italiana abraza la excelencia',
      description: 'Experiencia gastronómica de autor en Portofino Costa, combinando ingredientes selectos importados directamente de Italia con la frescura del mar local.',
      viewMenu: 'Ver Menú',
      bookNow: 'Reservar Mesa',
      scroll: 'Deslizar para descubrir',
    },
    essence: {
      tagline: 'ALTA GASTRONOMÍA DE AUTOR',
      title: 'Una mirada contemporánea a la herencia italiana',
      p1: 'En Luminara, cada plato cuenta una historia de mares antiguos, tierras fértiles y secretos transmitidos a través de generaciones. Ubicado frente al mar de la costa premium, nuestro restaurante rinde homenaje a la pureza del producto y la sofisticación del minimalismo culinario italiano.',
      p2: 'Bajo la dirección del Chef Matteo Rossi, diseñamos un viaje sensorial que respeta las recetas tradicionales mientras las eleva con técnicas de vanguardia. Cada porción de pasta fresca se amasa a mano diariamente en nuestro taller con harina Semola di Grano Duro de la región de Puglia.',
      p3: 'La frescura del mar mediterráneo se fusiona con trufas de Alba, quesos Parmigiano Reggiano de 36 meses de curación y aceites de oliva infusionados con cítricos costeros, brindando un festín inigualable que trasciende lo convencional.',
      badge1: '100% Artesanal',
      badge1Sub: 'Pasta fresca hecha a mano',
      badge2: 'Importaciones DOCG',
      badge2Sub: 'Ingredientes de origen certificado',
      badge3: 'Bodega de Élite',
      badge3Sub: 'Más de 300 referencias premium',
    },
    menu: {
      title: 'La Experiencia Gastronómica',
      subtitle: 'Creaciones sublimes que integran alma, sabor y refinamiento italiano.',
      viewAll: 'Ver Carta Completa',
      close: 'Cerrar Carta',
      pairingLabel: 'Maridaje Sugerido',
      currency: '€',
      interactiveNotice: '* Todos nuestros platos se elaboran al momento. Por favor notifique cualquier alergia a nuestro personal.',
    },
    wine: {
      title: 'La Bodega Subterránea',
      subtitle: 'Una colección curada de joyas enológicas seleccionadas personalmente por nuestro sommelier.',
      categoryBlancos: 'Blancos Prestigiados',
      categoryTintos: 'Grandes Tintos Italianos',
      categoryEspumosos: 'Espumosos & Champagne',
      categoryCopas: 'Vinos por Copa',
      sommelierNote: 'Nota del Sommelier',
      sommelierQuote: '"El vino no es solo una bebida, es el hilo conductor de la memoria gastronómica de Italia. Hemos reunido añadas históricas que narran la mineralidad de los volcanes y la calidez del sol costero."',
      bottleLabel: 'Botella',
      glassLabel: 'Copa',
    },
    gallery: {
      title: 'Momentos Luminara',
      subtitle: 'Un recorrido visual por nuestros espacios suspendidos en el tiempo, detalles culinarios y la atmósfera cálida de nuestras noches iluminadas por velas.',
    },
    events: {
      title: 'Eventos Privados',
      subtitle: 'Celebre sus momentos más significativos en un entorno de privacidad y sofisticación absoluta frente al mar.',
    },
    chef: {
      title: 'El Creador',
      subtitle: 'Chef de Cuisine Matteo Rossi',
      bio: 'Criado entre los olivares de la Toscana y entrenado en las cocinas más exclusivas de Milán y París, el Chef Matteo Rossi define su cocina como un equilibrio perfecto entre la nostalgia familiar y la precisión contemporánea. Su filosofía se basa en "la impecable sencillez": utilizar no más de cuatro elementos centrales en el plato, logrando que cada uno alcance su máxima y más sublime expresión de sabor.',
      sigSignature: 'M. Rossi',
    },
    booking: {
      title: 'Planifique su Experiencia',
      subtitle: 'Reserve su mesa en nuestro salón principal o terraza panorámica frente al mar. Le sugerimos reservar con antelación.',
      instructions: 'Las reservas online se confirman en tiempo real. Para grupos mayores a 8 personas o eventos especiales, por favor contáctenos directamente por WhatsApp.',
      fieldName: 'Nombre Completo',
      fieldEmail: 'Correo Electrónico',
      fieldPhone: 'Número de Teléfono',
      fieldDate: 'Fecha',
      fieldTime: 'Hora',
      fieldGuests: 'Número de Comensales',
      fieldDietary: 'Restricciones Alimenticias / Alergias',
      dietaryPlaceholder: 'Ej. Vegetariano, alergia a mariscos, sin gluten...',
      fieldOccasion: 'Ocasión Especial',
      occasionNone: 'Ninguna',
      occasionBday: 'Cumpleaños',
      occasionAnniv: 'Aniversario',
      occasionBiz: 'Reunión de Negocios',
      occasionOther: 'Otro Motivo',
      buttonSubmit: 'Confirmar Reserva de Mesa',
      buttonSubmitting: 'Procesando Reserva...',
      successTitle: 'Reserva Confirmada',
      successMessage: 'Grazie Mille. Su mesa en Luminara Ristorante ha sido reservada con éxito.',
      successDetail: 'Hemos enviado una confirmación elegante a su correo electrónico con los detalles del acceso. Esperamos brindarle una velada extraordinaria.',
      buttonClose: 'Entendido, Cerrar',
    },
    contact: {
      title: 'Conecte con Nosotros',
      subtitle: 'Encuéntrenos en la bahía o envíenos un mensaje directo.',
      chatWithUs: 'Escríbanos por WhatsApp',
      findUs: 'Nuestra Ubicación',
      directionLabel: 'Dirección',
      howToGetThere: 'Cómo Llegar',
      howToGetThereDesc: 'Ubicado en el acantilado sur del paseo marítimo, acceso directo por la Avenida Costera de Portofino, entrada exclusiva con servicio de Valet Parking privado gratuito.',
      phoneLabel: 'Reserva Telefónica',
      emailLabel: 'Consultas y Eventos',
      hoursLabel: 'Horario de Apertura',
      hoursWeek: 'Martes a Viernes · 13:00 - 16:30 | 19:30 - Midnight',
      hoursWeekend: 'Sábados, Domingos y Festivos · 12:30 - Midday continuous | 19:00 - 01:00',
    },
  },
  en: {
    nav: {
      home: 'Home',
      essence: 'The Essence',
      menu: 'The Menu',
      wine: 'Wine List',
      gallery: 'Gallery',
      chef: 'The Chef',
      contact: 'Contact',
      book: 'Book Table',
    },
    hero: {
      subtitle: 'LUMINARA RISTORANTE',
      titleAccent: 'Where Italian tradition embraces excellence',
      description: 'Signature culinary experience in Portofino Bay, blending select ingredients imported directly from Italy with the absolute freshness of the local sea.',
      viewMenu: 'View Menu',
      bookNow: 'Book Table',
      scroll: 'Scroll to discover',
    },
    essence: {
      tagline: 'SIGNATURE FINE DINING',
      title: 'A contemporary gaze upon Italian heritage',
      p1: 'At Luminara, every dish tells a story of ancient seas, fertile lands, and culinary secrets passed down through generations. Located in front of the premium coastal sea, our restaurant honors the purity of the raw ingredient and the sophistication of Italian minimalism.',
      p2: 'Under executive Chef Matteo Rossi, we design a sensory journey respecting traditional recipes while elevating them with avant-garde culinary techniques. Every portion of fresh pasta is hand-kneaded daily in our workshop using Semola di Grano Duro from Puglia.',
      p3: 'Mediterranean tides merge with white truffles from Alba, 36-month aged Parmigiano Reggiano, and lemon-infused coastal olive oils, bringing forth a timeless feast that surpasses regular fine dining.',
      badge1: '100% Handcrafted',
      badge1Sub: 'Daily handmade fresh pasta',
      badge2: 'DOCG Imports',
      badge2Sub: 'Certified origin ingredients',
      badge3: 'Elite Cellar',
      badge3Sub: 'Over 300 premium vintages',
    },
    menu: {
      title: 'Our Gastronomic Journey',
      subtitle: 'Sublime creations that seamlessly integrate the soul, flavor, and Italian culinary refinement.',
      viewAll: 'View Complete Menu',
      close: 'Close Menu',
      pairingLabel: 'Suggested Wine Pairing',
      currency: '€',
      interactiveNotice: '* Every dish is prepared à la minute. Please notify our elite service staff of any food restrictions.',
    },
    wine: {
      title: 'The Underground Cellar',
      subtitle: 'A beautifully curated list of wine masterpieces personally selected by our head sommelier.',
      categoryBlancos: 'Prestigious Whites',
      categoryTintos: 'Grand Italian Reds',
      categoryEspumosos: 'Sparkling & Champagne',
      categoryCopas: 'Wines by the Glass',
      sommelierNote: 'Sommelier\'s Note',
      sommelierQuote: '"Wine is not just a drink; it is the copper wire of Italy\'s culinary memory. We gathered master vintages that speak of volcanic minerality and sunset coastal warmth."',
      bottleLabel: 'Bottle',
      glassLabel: 'Glass',
    },
    gallery: {
      title: 'Captured Moments',
      subtitle: 'A sensory tour of our spaces suspended in time, detailed plating, and the glowing warmth of our candlelit evenings.',
    },
    events: {
      title: 'Private Events',
      subtitle: 'Celebrate your most significant moments in an environment of total privacy and coastal sophistication.',
    },
    chef: {
      title: 'The Creator',
      subtitle: 'Chef de Cuisine Matteo Rossi',
      bio: 'Raised amid Tuscan olive groves and trained in legendary Michelin-starred kitchens in Milan and Paris, Chef Matteo Rossi defines his cuisine as a delicate balance between home nostalgia and contemporary discipline. His philosophy rests on "impeccable simplicity": utilizing no more than four main ingredients, letting each sing in its absolute truest flavor.',
      sigSignature: 'M. Rossi',
    },
    booking: {
      title: 'Plan Your Experience',
      subtitle: 'Reserve your table in our main dining salon or coastal panoramic terrace. We highly recommend booking in advance.',
      instructions: 'Online reservations are confirmed in real time. For parties larger than 8 guests or private events, please write to us via WhatsApp.',
      fieldName: 'Full Name',
      fieldEmail: 'Email Address',
      fieldPhone: 'Phone Number',
      fieldDate: 'Date',
      fieldTime: 'Time Slot',
      fieldGuests: 'Number of Guests',
      fieldDietary: 'Dietary Restrictions / Allergies',
      dietaryPlaceholder: 'e.g., Vegetarian, shellfish allergy, gluten-free...',
      fieldOccasion: 'Special Occasion',
      occasionNone: 'None',
      occasionBday: 'Birthday',
      occasionAnniv: 'Anniversary',
      occasionBiz: 'Business Meeting',
      occasionOther: 'Other Celebration',
      buttonSubmit: 'Confirm Table Booking',
      buttonSubmitting: 'Securing your table...',
      successTitle: 'Reservation Confirmed',
      successMessage: 'Grazie Mille. Your table at Luminara Ristorante is secured.',
      successDetail: 'A sophisticated confirmation email has been dispatched. We look forward to offering you an unforgettable evening with us.',
      buttonClose: 'Understood, Close',
    },
    contact: {
      title: 'Connect with Us',
      subtitle: 'Find us on the south cliffs or send us a direct message.',
      chatWithUs: 'Message via WhatsApp',
      findUs: 'Our Location',
      directionLabel: 'Address',
      howToGetThere: 'How to Arrive',
      howToGetThereDesc: 'Nestled on the cliff overlooking the bay. Direct access via Portofino Coastal Avenue, featuring complimentary private valet parking for all guests.',
      phoneLabel: 'Direct Telephone',
      emailLabel: 'Inquiries & Private Dinners',
      hoursLabel: 'Opening Hours',
      hoursWeek: 'Tuesday to Friday · 1:00 PM - 4:30 PM | 7:30 PM - Midnight',
      hoursWeekend: 'Saturday, Sunday & Holidays · 12:30 PM - Noon continuous | 7:00 PM - 1:00 AM',
    },
  },
};

export const menuCategories: MenuCategory[] = [
  {
    id: 'antipasti',
    name: 'Antipasti',
    items: [
      {
        id: 'anti-1',
        nameIt: 'Carpaccio di Ricciola',
        nameSub: 'Carpaccio de Pez Limón de Costa',
        description: 'Láminas finas de pez limón fresco, emulsión de oliva de Liguria, pistachos sicilianos tostados, gel de limón de Amalfi y brotes marinos organicos.',
        price: '29',
        badge: 'Signature',
        pairing: 'Franciacorta Satèn DOCG',
      },
      {
        id: 'anti-2',
        nameIt: 'Fiori di Zucca Ripieni',
        nameSub: 'Flores de Calabacín Rellenas',
        description: 'Flores de calabacín crujientes rellenas de ricotta de búfala artesanal, trufa negra de verano rallada y un hilo de miel orgánica de castaño.',
        price: '26',
        pairing: 'Vermentino di Gallura DOCG',
      },
      {
        id: 'anti-3',
        nameIt: 'Burrata e Fichi Caramellati',
        nameSub: 'Burrata de Andria con Higos',
        description: 'Cremosa burrata fresca de Puglia, higos caramelizados al sándalo de Módena envejecido 15 años, jamón de Parma crujiente, piñones y rúcula selvática.',
        price: '28',
        badge: 'Favorito',
        pairing: 'Soave Classico DOC',
      },
      {
        id: 'anti-4',
        nameIt: 'Polpo Croccante su Crema di Patate',
        nameSub: 'Pulpo Crujiente sobre Crema de Patatas',
        description: 'Tentáculo de pulpo mediterráneo braseado al carbón de olivo, sobre una emulsión sedosa de patatas aromatizadas con azafrán de los Abruzos y aceitunas Taggiasche.',
        price: '34',
        pairing: 'Fiano di Avellino DOCG',
      },
    ],
  },
  {
    id: 'primi',
    name: 'Primi Piatti',
    items: [
      {
        id: 'primi-1',
        nameIt: 'Tagliolini all’Astice e Tartufo',
        nameSub: 'Tagliolini de Bogavante y Trufa',
        description: 'Pasta artesanal al huevo estirada a mano, bogavante azul del Atlántico saltado al coñac, mantequilla de trufa artesanal d’Alba, emulsión de sus corales y láminas de trufa fresca.',
        price: '46',
        badge: 'Exclusivo',
        pairing: 'Cervaro della Sala IGT',
      },
      {
        id: 'primi-2',
        nameIt: 'Ravioli di Zucca alla Mantovana',
        nameSub: 'Raviolis de Calabaza Asada',
        description: 'Pasta fresca rellena de puré de calabaza dulce de Mantua, galleta Amaretto triturada, Parmigiano Reggiano 36 meses y un velo de mantequilla noisette aromatizada con salvia fresca.',
        price: '36',
        pairing: 'Gewürztraminer Alto Adige DOC',
      },
      {
        id: 'primi-3',
        nameIt: 'Cappellacci al Coda alla Vaccinara',
        nameSub: 'Cappellacci de Rabo de Toro',
        description: 'Sombreros de pasta rellenos de rabo de buey estofado lentamente durante 12 horas en vino tinto Chianti Classico, servidos sobre reducción cremosa de Pecorino Romano DOCG.',
        price: '39',
        badge: 'Chef Choice',
        pairing: 'Brunello di Montalcino DOCG',
      },
      {
        id: 'primi-4',
        nameIt: 'Risotto ai Frutti di Mare e Zafferano',
        nameSub: 'Risotto Acquerello con Mariscos',
        description: 'Arroz Acquerello envejecido de edición limitada, cocido en un elixir de mariscos de roca, infusión de azafrán puro de Cerdeña, coronado con carpaccio de vieiras sopleteado.',
        price: '44',
        pairing: 'Greco di Tufo DOCG',
      },
    ],
  },
  {
    id: 'secondi',
    name: 'Secondi',
    items: [
      {
        id: 'seco-1',
        nameIt: 'Filetto di Manzo al Brunello',
        nameSub: 'Solomillo de Ternera Premium',
        description: 'Solomillo de ternera madurada 45 días, marcado al grill, sobre reducción sedosa de vino Brunello di Montalcino, foie gras sellado y milhojas de patata trufada.',
        price: '52',
        badge: 'Lujo',
        pairing: 'Sassicaia Bolgheri DOCG',
      },
      {
        id: 'seco-2',
        nameIt: 'Trancio di Spigola in Crosta di Sale',
        nameSub: 'Lubina en Costra de Sal de Trapani',
        description: 'Lomo de lubina salvaje de la costa, asado suavemente en costra de sal marina orgánica y hierbas del acantilado, servido con espárragos al vapor y salsa cítrica de hinojo silvestre.',
        price: '45',
        pairing: 'Vermentino Bolgheri DOC',
      },
      {
        id: 'seco-3',
        nameIt: 'Costolette d’Agnello al Rosmarino',
        nameSub: 'Costillar de Cordero Lechal',
        description: 'Costillitas de cordero lechal de los Pirineos marinadas con hierbas aromáticas, asadas al horno de leña, acompañadas de chalotas caramelizadas al Vin Santo y puré suave de alcachofas de Caraglio.',
        price: '48',
        pairing: 'Amarone della Valpolicella DOCG',
      },
    ],
  },
  {
    id: 'dolci',
    name: 'Dolci & Formaggi',
    items: [
      {
        id: 'dolci-1',
        nameIt: 'Tiramisù Sospeso',
        nameSub: 'Tiramisú Contemporáneo',
        description: 'Bizcocho Savoiardi empapado en Espresso de Etiopía de tres tostados y Amaretto Disaronno, crema aireada de Mascarpone purísimo de granja y una esfera de chocolate belga.',
        price: '18',
        badge: 'Legendario',
        pairing: 'Passito di Pantelleria DOC',
      },
      {
        id: 'dolci-2',
        nameIt: 'Sfera al Limone di Sorrento',
        nameSub: 'Esfera Cítrica de Sorrento',
        description: 'Cúpula brillante de gelatina de limón dulce, mousse de chocolate blanco belga premium, corazón fluido de lemon curd y tierra crujiente de almendras de Avola.',
        price: '16',
        pairing: 'Moscato d’Asti DOCG',
      },
      {
        id: 'dolci-3',
        nameIt: 'Selezione di Formaggi DOCG',
        nameSub: 'Selección de Quesos Italianos Nobles',
        description: 'Tabla degustación de Gorgonzola Picante de Piedmont, Pecorino Sardo envejecido bajo tierra, Parmigiano Vacche Rosse de 40 meses, servidos con pan carasau de Cerdeña y mermelada artesanal de higo.',
        price: '24',
        pairing: 'Recioto della Valpolicella DOC',
      },
    ],
  },
];

export const wineCategories: WineCategory[] = [
  {
    id: 'espumosos',
    name: 'Espumosos & Champagne',
    items: [
      {
        id: 'wine-1',
        name: 'Giulio Ferrari Riserva del Fondatore',
        winery: 'Ferrari Trento',
        region: 'Trentino',
        year: '2012',
        priceBottle: '220',
        description: 'Considerado el espumoso más icónico de Italia. Elegancia suprema con notas de brioche tostado y miel.',
      },
      {
        id: 'wine-2',
        name: 'Bellavista Franciacorta Alma Gran Cuvée',
        winery: 'Bellavista',
        region: 'Lombardia',
        year: 'NV',
        priceGlass: '18',
        priceBottle: '85',
        description: 'Un espumoso sutil con aromas frutales vibrantes y una cremosidad persistente en el paladar.',
      },
      {
        id: 'wine-3',
        name: 'Dom Pérignon Vintage',
        winery: 'Moët & Chandon',
        region: 'Champagne, Francia',
        year: '2013',
        priceBottle: '390',
        description: 'Profundidad mineral exuberante con toques característicos de jengibre y especias dulces.',
      },
    ],
  },
  {
    id: 'blancos',
    name: 'Blancos Prestigiados',
    items: [
      {
        id: 'wine-4',
        name: 'Cervaro della Sala Chardonnay',
        winery: 'Marchesi Antinori',
        region: 'Umbria',
        year: '2021',
        priceGlass: '26',
        priceBottle: '145',
        description: 'Chardonnay sublime con toques de vainilla, mantequilla fundida e increíble frescura mineral.',
      },
      {
        id: 'wine-5',
        name: 'Gavi di Gavi Black Label',
        winery: 'La Scolca',
        region: 'Piemonte',
        year: '2022',
        priceBottle: '95',
        description: 'Fresco e intenso, con aromas almendrados refinados y una acidez perfectamente acoplada al marisco.',
      },
      {
        id: 'wine-6',
        name: 'Vermentino Bolgheri SoloSole',
        winery: 'Poggio al Tesoro',
        region: 'Toscana',
        year: '2022',
        priceGlass: '15',
        priceBottle: '68',
        description: 'Aromas florales silvestres y notas pronunciadas de albaricoque y salinidad atlántica.',
      },
    ],
  },
  {
    id: 'tintos',
    name: 'Grandes Tintos Italianos',
    items: [
      {
        id: 'wine-7',
        name: 'Sassicaia Tenuta San Guido',
        winery: 'Tenuta San Guido',
        region: 'Toscana (Bolgheri)',
        year: '2019',
        priceBottle: '450',
        description: 'Un hito histórico. La leyenda viviente del "Super Toscano" que combina potencia sedosa y especias.',
      },
      {
        id: 'wine-8',
        name: 'Brunello di Montalcino Riserva',
        winery: 'Biondi Santi',
        region: 'Toscana',
        year: '2016',
        priceBottle: '340',
        description: 'Un clásico inmortal. Aroma de violetas silvestres, tabaco curado y cuero aristocrático.',
      },
      {
        id: 'wine-9',
        name: 'Barolo Bricco Rocche',
        winery: 'Ceretto',
        region: 'Piemonte',
        year: '2018',
        priceBottle: '210',
        description: 'Vino regio y robusto de Nebbiolo. Notas intensas de trufa negra, cerezas maceradas y humo de encina.',
      },
      {
        id: 'wine-10',
        name: 'Tignanello',
        winery: 'Marchesi Antinori',
        region: 'Toscana',
        year: '2020',
        priceGlass: '42',
        priceBottle: '195',
        description: 'Cuerpo exuberante de bayas negras, regaliz y granos de cacao profundamente tostados.',
      },
    ],
  },
  {
    id: 'copas',
    name: 'Vinos de Selección por Copa',
    items: [
      {
        id: 'wine-11',
        name: 'Chianti Classico Gran Selezione',
        winery: 'Castello di Ama',
        region: 'Toscana',
        year: '2019',
        priceGlass: '18',
        priceBottle: '85',
        description: 'Sabor jugoso de frutos rojos de bosque con una estructura balanceada de romero y pimienta.',
      },
      {
        id: 'wine-12',
        name: 'Amarone della Valpolicella Valpantena',
        winery: 'Bertani',
        region: 'Veneto',
        year: '2018',
        priceGlass: '24',
        priceBottle: '115',
        description: 'Vino maduro e imponente, caracterizado por sus aromas persistentes de pasas de uva, ciruelas y café.',
      },
      {
        id: 'wine-13',
        name: 'Fiano di Avellino Radici',
        winery: 'Mastroberardino',
        region: 'Campania',
        year: '2021',
        priceGlass: '14',
        priceBottle: '58',
        description: 'Un blanco volcánico seco con notas de avellana madurada, pera asada y un final refrescante de flores blancas.',
      },
    ],
  },
];

export const galleryItems = [
  {
    id: 'gal-1',
    image: '/src/assets/images/hero_dish_1780364911889.png',
    titleEs: 'Nuestra Pasta Insignia',
    titleEn: 'Signature Pasta Delight',
    categoryEs: 'Gastronomía',
    categoryEn: 'Gastronomy',
  },
  {
    id: 'gal-2',
    image: '/src/assets/images/restaurant_interior_1780364932872.png',
    titleEs: 'Terraza de Velas al Atardecer',
    titleEn: 'Sunset Candlelit Terrace',
    categoryEs: 'Atmósfera',
    categoryEn: 'Atmosphere',
  },
  {
    id: 'gal-3',
    image: '/src/assets/images/wine_cellar_1780364963365.png',
    titleEs: 'Colección de Añadas Históricas',
    titleEn: 'Vintages Private Collection',
    categoryEs: 'Bodega',
    categoryEn: 'Wine Cellar',
  },
  {
    id: 'gal-4',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80&w=800',
    titleEs: 'Maridajes en un ambiente íntimo',
    titleEn: 'Wine Tastings in Intimate Spaces',
    categoryEs: 'Momentos',
    categoryEn: 'Moments',
  },
  {
    id: 'gal-5',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    titleEs: 'El Fuego del Horno de Piedra',
    titleEn: 'Crafting the Perfect Crust',
    categoryEs: 'Cocina',
    categoryEn: 'Kitchen',
  },
  {
    id: 'gal-6',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
    titleEs: 'Nuestras Noches Íntimas',
    titleEn: 'Charming Candlelit Tables',
    categoryEs: 'Salón',
    categoryEn: 'Salon',
  },
];
